$(document).ready(function(){
	$('#stone').click(function(){
		console.log('Stone');
	});
	$('#paper').click(function(){
		console.log('paper');
	});
	$('#scissor').click(function(){
		console.log('Scissor');
	});
})